[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

# Add this new redirect for /api/mcp
[[redirects]]
  from = "/api/mcp"
  to = "/.netlify/functions/mcp"
  status = 200

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/mcp"
  status = 200

[[redirects]]
  from = "/sse"
  to = "/.netlify/functions/mcp"
  status = 200

[[redirects]]
  from = "/api/sse"
  to = "/.netlify/functions/sse"
  status = 200
