[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/mcp"
  status = 200

# Redirect /sse to /mcp for backward compatibility
[[redirects]]
  from = "/sse"
  to = "/.netlify/functions/mcp"
  status = 200
