[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

# JSON-RPC over HTTP endpoints
[[redirects]]
  from = "/api/mcp"
  to = "/.netlify/functions/mcp"
  status = 200

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/mcp"
  status = 200

# SSE endpoints - make sure these point to sse.js, not mcp.js
[[redirects]]
  from = "/sse"
  to = "/.netlify/functions/sse"
  status = 200

[[redirects]]
  from = "/api/sse"
  to = "/.netlify/functions/sse"
  status = 200

[[redirects]]
  from = "/v1"
  to = "/.netlify/functions/mcp-streamable"
  status = 200
